---
title: "Flexible sexual appetite - Analysis Report"
author: "Malika Ihle"
date: "November 9, 2017"
output: pdf_document
---

```{r, echo=FALSE, results="hide", message=FALSE, warnings=FALSE, include =FALSE}
source('C:\\Users\\malika.ihle\\Documents\\_Malika_Florida\\Stats&Analyses\\FlexibleSexualAppetite\\DataAnalyses.R')
```

# descriptive numbers

## dead females during training
```{r, echo=TRUE}
DeadFemales   
AliveFemales
chisq.test(rbind(DeadFemales,AliveFemales))
```
## dead males during tests

```{r, echo=FALSE}
table(MY_TABLE_MaleTest$ReasonExclusion[MY_TABLE_MaleTest$ExcludeYN == TRUE]) 
```
```{r, echo=TRUE}
chisq.test(rbind(c(10,3),c(97,104)))
```

# Bug test
```{r, echo=FALSE}
summary(mod1)
```

# Termite test
```{r, echo=FALSE}
summary(mod2)
```

## equality of motivation to feed
```{r, echo=FALSE}
t.test (log(MY_TABLE_TermiteTest$LatencyAttack[MY_TABLE_TermiteTest$Trt == "RedPreference"]), 
          log(MY_TABLE_TermiteTest$LatencyAttack[MY_TABLE_TermiteTest$Trt == "RedAverse"]))
```

# Male test
```{r, echo=FALSE}
summary(mod3)
```
## equality of male motivation to court  
videos not watched yet  

# FID repeatability 
```{r, echo=FALSE}
summary(mod4)
```

# Odds ratio

## Bug
```{r, echo=FALSE, message=FALSE, warnings=FALSE,}
exp(cbind(OR=coef(mod1), confint(mod1)))[2,] 
```

## Termite
```{r, echo=FALSE, message=FALSE, warnings=FALSE,}
exp(cbind(OR=coef(mod2), confint(mod2)))[2,]
```

## Male
```{r, echo=FALSE, message=FALSE, warnings=FALSE,}
exp(cbind(OR=coef(mod3), confint(mod3)))[2,]
```

# Termite graph against 50/50
```{r, echo=FALSE}
ggplot(MY_TABLE_TermiteTest,aes(x=AttackNewRedYN,group=Trt,fill=Trt))+
  geom_histogram(position="dodge",binwidth=0.25)+theme_bw()
```

# Male graph against 50/50
```{r, echo=FALSE}
ggplot(MY_TABLE_MaleTestValid,aes(x=CannibalizedRedYN,group=Trt,fill=Trt))+
  geom_histogram(position="dodge",binwidth=0.25)+theme_bw()
```



